Update script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,45 +1,16 @@
 #! /bin/sh
 #
-# Configuration script for a Yorick plugin.
+# Configuration script for YLib plugin.
 #
 #------------------------------------------------------------------------------
 #
-# Copyright (C) 2012 Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>
+# YLib (Yorick Library) is licensed under the MIT "Expat" License.
 #
-# This software is governed by the CeCILL-C license under French law and
-# abiding by the rules of distribution of free software.  You can use, modify
-# and/or redistribute the software under the terms of the CeCILL-C license as
-# circulated by CEA, CNRS and INRIA at the following URL
-# "http://www.cecill.info".
-#
-# As a counterpart to the access to the source code and rights to copy,
-# modify and redistribute granted by the license, users are provided only
-# with a limited warranty and the software's author, the holder of the
-# economic rights, and the successive licensors have only limited liability.
-#
-# In this respect, the user's attention is drawn to the risks associated with
-# loading, using, modifying and/or developing or reproducing the software by
-# the user in light of its specific status of free software, that may mean
-# that it is complicated to manipulate, and that also therefore means that it
-# is reserved for developers and experienced professionals having in-depth
-# computer knowledge. Users are therefore encouraged to load and test the
-# software's suitability as regards their requirements in conditions enabling
-# the security of their systems and/or data to be ensured and, more
-# generally, to use and operate it in the same conditions as regards
-# security.
-#
-# The fact that you are presently reading this means that you have had
-# knowledge of the CeCILL-C license and that you accept its terms.
+# Copyright (C) 2012-2018, Éric Thiébaut <https://github.com/emmt/ylib>
 #
 #------------------------------------------------------------------------------
 
-# The following default values are specific to the package.  They can be
-# overwritten by options on the command line.
-cfg_cflags=
-cfg_deplibs='-lgsl -lgslcblas'
-cfg_ldflags=
-
-# The other values are pretty general.
+# Temporaries.
 cfg_tmpdir=.
 cfg_tmpfile="$cfg_tmpdir/cfg-$$"
 cfg_debug=no
@@ -63,36 +34,33 @@ cfg_opt_value () { echo "$*" | sed 's/^--[^=]*=//'; }
 
 cfg_despace () { echo "$*" | sed 's/ /\\ /g'; }
 
-cfg_subst_macro () {
-  local s
-  local t
-  s=$*
-  for t in "/" "%" "@" "," "-"; do
-    case "$s" in
-      *$t* )
-        ;;
-      * )
-        break
-    esac
-  done
-  if test "$t" = "-"; then
-    cfg_die "No valid separator found"
-  fi
-  s='[ 	]*'
-  echo "s${t}^${s}${1}${s}=.*${t}${1}=${2}${t}"
+cfg_add_rule () {
+    local s t
+    s=$*
+    for t in "/" "%" "@" "|" "#" "," "-"
+    do
+        case "$s" in
+            *$t* ) ;;
+            * ) break
+        esac
+    done
+    test "$t" = "-" && cfg_die "No valid separator found"
+    s='[ 	]*'
+    s="s${t}^${s}${1}${s}=.*${t}${1}=${2}${t}"
+    if test "x$cfg_filter" = "x"
+    then
+        cfg_filter="$s"
+    else
+        cfg_filter="$cfg_filter;$s"
+    fi
 }
 
 cfg_help () {
   cat <<EOF
 usage: $cfg_progname [-h|--help] [--yorick=PATH_TO_YORICK]
 options:
-  --arch=OS-CPU        Architecture [$cfg_arch].
   --yorick=PATH        Path to Yorick executable [$cfg_yorick].
-  --cflags=CFLAGS      Additional compiler flags [$cfg_cflags], for instance:
-                         --cflags='-Isomedir'
-  --deplibs=DEPLIBS    Flags for dependencies [$cfg_deplibs], for instance:
-                         --deplibs='-Lsomedir -lsomelib'
-  --ldflags=LDFLAGS    Additional linker flags [$cfg_ldflags].
+  --arch=OS-CPU        Architecture [$cfg_arch].
   --debug              Turn debug mode on (for this script).
   -h, --help           Print this help and exit.
 EOF
@@ -106,17 +74,16 @@ fi
 
 cfg_os=$(uname -s | tr A-Z a-z)
 if test "x$cfg_os" = "x"; then
-  cfg_os="unknown"
+    cfg_os="unknown"
 fi
 cfg_cpu=$(uname -m | tr A-Z a-z)
 if test "x$cfg_cpu" = "x"; then
-  cfg_cpu="unknown"
+    cfg_cpu="unknown"
 else
-  case "$cfg_cpu" in i?86 ) cfg_cpu="ix86";; esac
+    case "$cfg_cpu" in i?86 ) cfg_cpu="ix86";; esac
 fi
 cfg_arch=${cfg_os}-${cfg_cpu}
 cfg_yorick=yorick
-cfg_prefix=/usr/local
 while test $# -ge 1; do
   cfg_arg=$1
   shift
@@ -125,20 +92,11 @@ while test $# -ge 1; do
       cfg_help
       exit 0
       ;;
-    --debug)
-      cfg_debug=yes
-      ;;
     --arch=*)
       cfg_arch=$(cfg_opt_value "$cfg_arg")
       ;;
-    --cflags=*)
-      cfg_cflags=$(cfg_opt_value "$cfg_arg")
-      ;;
-    --deplibs=*)
-      cfg_deplibs=$(cfg_opt_value "$cfg_arg")
-      ;;
-    --ldflags=*)
-      cfg_ldflags=$(cfg_opt_value "$cfg_arg")
+    --debug)
+      cfg_debug=yes
       ;;
     --yorick=*)
       cfg_yorick=$(cfg_opt_value "$cfg_arg")
@@ -149,11 +107,8 @@ while test $# -ge 1; do
 done
 
 case "$cfg_arch" in
-  mswin )
-    cfg_exe_sfx=.exe
-    ;;
-  * )
-    cfg_exe_sfx=
+  mswin) cfg_exe_sfx=".exe";;
+  *)     cfg_exe_sfx=""
 esac
 
 # Search Yorick in the path:
@@ -172,7 +127,7 @@ fi
 if test "x$cfg_yorick" = "xyorick" \
   -o ! -f "$cfg_yorick" \
   -o ! -x "$cfg_yorick"; then
-  echo >&2 "Yorick excutable not found."
+  echo >&2 "Yorick executable not found."
   echo >&2 "Try to specify the path with option --yorick=..."
   exit 1
 fi
@@ -200,16 +155,16 @@ else
   cfg_src="$cfg_srcdir/Makefile"
 fi
 
-cfg_s0=$(cfg_subst_macro "Y_EXE"       "$cfg_yorick")
-cfg_s1=$(cfg_subst_macro "Y_MAKEDIR"   "$cfg_ymkdir")
-cfg_s2=$(cfg_subst_macro "Y_EXE_HOME"  "$cfg_yhome")
-cfg_s3=$(cfg_subst_macro "Y_EXE_SITE"  "$cfg_ysite")
-cfg_s4=$(cfg_subst_macro "PKG_CFLAGS"  "$cfg_cflags")
-cfg_s5=$(cfg_subst_macro "PKG_DEPLIBS" "$cfg_deplibs")
-cfg_s6=$(cfg_subst_macro "PKG_LDFLAGS" "$cfg_ldflags")
-cfg_s7=$(cfg_subst_macro "srcdir"      "$cfg_srcdir")
-sed < "$cfg_src" > "$cfg_dst" \
-  -e "$cfg_s0;$cfg_s1;$cfg_s2;$cfg_s3;$cfg_s4;$cfg_s5;$cfg_s6;$cfg_s7"
+cfg_filter=""
+cfg_add_rule "Y_EXE"       "$cfg_yorick"
+cfg_add_rule "Y_MAKEDIR"   "$cfg_ymkdir"
+cfg_add_rule "Y_EXE_HOME"  "$cfg_yhome"
+cfg_add_rule "Y_EXE_SITE"  "$cfg_ysite"
+cfg_add_rule "PKG_CFLAGS"  "$cfg_cflags"
+cfg_add_rule "PKG_DEPLIBS" "$cfg_deplibs"
+cfg_add_rule "PKG_LDFLAGS" "$cfg_ldflags"
+cfg_add_rule "srcdir"      "$cfg_srcdir"
+sed < "$cfg_src" > "$cfg_dst" -e "$cfg_filter"
 
 if test "$cfg_inplace" = "yes"; then
   rm -f "$cfg_src"
@@ -217,11 +172,3 @@ fi
 
 echo "Makefile has been updated."
 echo "You can run 'make' and 'make install' now."
-
-# Local Variables:
-# mode: sh
-# tab-width: 8
-# indent-tabs-mode: nil
-# fill-column: 78
-# coding: utf-8
-# End:
